apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: mysql
  app.kubernetes.io/component: mysql
  app.kubernetes.io/name: mysql
resources:
- ../../../upstream/env/platform-agnostic/mysql
- ../../overlays/application/application.yaml
images:
- name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/mysql
  newTag: '5.6'
  newName: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/mysql
