apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline
resources:
- config-map.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
images:
- name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/api-server
  newTag: 0.2.5
  newName: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/api-server
