apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemon-set.yaml
commonLabels:
  kustomize.component: gpu-driver
images:
- name: uhub.service.ucloud.cn/a4x-kubeflow/google-containers/pause
  newName: uhub.service.ucloud.cn/a4x-kubeflow/google-containers/pause
  newTag: '2.0'
- name: cos-nvidia-installer
  newName: cos-nvidia-installer
  newTag: fixed
