apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../upstream/env/platform-agnostic/minio
  - ../../upstream/env/platform-agnostic/mysql
  - kfp-tekton

# Identifier for application manager to apply ownerReference.
# The ownerReference ensures the resources get garbage collected
# when application is deleted.
commonLabels:
  app.kubernetes.io/name: kubeflow-pipelines
  app.kubernetes.io/component: ml-pipeline

# !!! If you want to customize the namespace,
# please also update base/cache-deployer/cluster-scoped/cache-deployer-clusterrolebinding.yaml
namespace: kubeflow

images:
  - name: mysql
    newTag: "5.6"
  - name: minio/minio
    newTag: RELEASE.2018-02-09T22-40-05Z
  - name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/api-server
    newName: uhub.service.ucloud.cn/a4x-kubeflow/aipipeline/api-server
    newTag: 0.4.0
  - name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/persistenceagent
    newName: uhub.service.ucloud.cn/a4x-kubeflow/aipipeline/persistenceagent
    newTag: 0.4.0
  - name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/frontend
    newName: uhub.service.ucloud.cn/a4x-kubeflow/aipipeline/frontend
    newTag: 0.4.0
  - name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/metadata-writer
    newName: uhub.service.ucloud.cn/a4x-kubeflow/aipipeline/metadata-writer
    newTag: 0.4.0
  - name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/scheduledworkflow
    newName: uhub.service.ucloud.cn/a4x-kubeflow/aipipeline/scheduledworkflow
    newTag: 0.4.0
