apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: ml-pipeline-visualizationserver
resources:
- deployment.yaml
- service.yaml
images:
- name: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/visualization-server
  newTag: 0.2.5
  newName: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/visualization-server
