apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ml-pipeline-ui
  name: ml-pipeline-ui
spec:
  selector:
    matchLabels:
      app: ml-pipeline-ui
  template:
    metadata:
      labels:
        app: ml-pipeline-ui
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: ml-pipeline-ui
        image: uhub.service.ucloud.cn/a4x-kubeflow/ml-pipeline/frontend
        imagePullPolicy: IfNotPresent
        env:
        - name: ALLOW_CUSTOM_VISUALIZATIONS
          value: "true"
        ports:
        - containerPort: 3000
      serviceAccountName: ml-pipeline-ui
